export interface IAuthOnuProps {
    userId: number | undefined,
    cityId?: number,
    oltId: number | string,
    slot?: number,
    pon: number,
    serialNumber: string,
    contract: number,
    modelOlt?: string,
    modelOnu?: string,
    typeOnu?: string,
    rxPower?: string,
    pppoeUser: string,
    pppPass?: string,
    wifiSSID?: string,
    wifiPass?: string,
}