export interface IAuthOnuProps {
    userId: number | undefined,
    cityId: number,
    oltId: number,
    ip: string[],
    slot?: number,
    pon: number,
    serialNumber: string,
    contract: number,
    isPizzaBox?: (boolean | number)[],
    type: string,
    model?: string,
    rxPower?: string,
    pppoeUser: string,
    pppPass?: string,
    wifiSSID?: string,
    wifiPass?: string,
}