export interface IAuthOnuProps {
    userId: number | undefined,
    cityId?: number,
    oltId: number | string,
    slot?: number,
    pon: number,
    serialNumber: string,
    contract: number,
    modelOlt?: string,
    modelOnu?: string,
    typeOnu?: string,
    rxPower?: string,
    cpf: string,
    pppoeUser: string,
    pppPass?: string,
    wifiSSIDBS?: string,
    wifiPassBS?: string,
    wifiSSID24?: string,
    wifiPass24?: string,
    wifiSSID58?: string,
    wifiPass58?: string,
    sipUser?: string,
    sipPass?: string
}